let id1=document.getElementById("id1")
let sp1=document.getElementById("span")
let id2=document.getElementById("id2")
console.log(id1)
// console.log(id1.matches("#id1"))
// console.log(id1.closest(".box2"))
console.log(id1.contains(sp1))
console.log(id1.contains(id1))
console.log(id1.contains(id2))
